import type { Metadata } from "next";
import { Header } from "../components/Header";

export const metadata: Metadata = {
	title: "Blog Application",
	description: "Generated by create Next.js, Sanity.io and Vercel",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
